on:
  push:
    branches:
      - 'main'
      
defaults:
  run:
    working-directory: frontend

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.1.1
        path: dist
